## 데이터 다운로드하기

In [11]:
import numpy as np
import pandas as pd

input_file = "emnist-digits-train.csv"
df_train = pd.read_csv(input_file, header=None)

## 다운받은 데이터 numpy로 변환

In [12]:
data_train = df_train.to_numpy()
data_train

array([[8, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

240000개의 데이터와 785개(타겟(1개), 픽셀데이터(784개))

In [13]:
data_train.shape

(240000, 785)

훈련셋 만들기

In [14]:
X_train = data_train[:, 1:]
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

타겟셋 만들기

In [15]:
y_train = data_train[:, 0]
y_train

array([8, 9, 6, ..., 1, 1, 0])

### 정규화는 이미지 프로세싱에서 자주 사용되는데, pixel intensities를 특정 범위(RGB 색상 범위의 경우 0~255) 내에 맞추려면 정규화가 필요하다. 

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scale = scaler.fit_transform(X_train.astype(np.float32))

### SGD (확률적 경사 하강법)

In [17]:
# from sklearn.linear_model import SGDClassifier
# sgd_clf = SGDClassifier(max_iter=10, tol=1e-4, random_state=42)
# sgd_clf.fit(X_train_scale, y_train)

In [18]:
# from sklearn.model_selection import cross_val_score

# cross_val_scores = cross_val_score(sgd_clf, X_train, y_train, cv=10, scoring="accuracy")

In [19]:
# cross_val_scores

In [20]:
# np.mean([0.92541667, 0.92775   , 0.92579167, 0.92625   , 0.92933333,
#        0.929125  , 0.92858333, 0.93075   , 0.92820833, 0.92970833])

max_iter(10): 0.928091666

### SVM 큰 데이터셋에 대해서는 성능이 좋은 편이 아니지만 그래도 한번 시도

SVM 알고리즘은 데이터를 정규화하는 것을 매우 추천한다, 하지만 앞에서 이미 했음

In [21]:
# from sklearn.svm import SVC

# svm_clf = SVC(gamma="auto", random_state=42)
# svm_clf.fit(X_train_scale, y_train)

In [22]:
# from sklearn.model_selection import cross_val_score

# svm_clf_cross_val_scores = cross_val_score(svm_clf, X_train, y_train, cv=10, scoring="accuracy")
# svm_clf_default_cross_val_scores

SVM의 시간복잡도는 O(n^3)으로 굉장히 높기 때문에 Bagging을 통해 훈련 튜플의 수를 줄이고 병렬처리를 적용하면 시간 단축을 할 수 있다고 한다

In [23]:
# from sklearn.svm import LinearSVC
# from sklearn.ensemble import BaggingClassifier
# estimator = LinearSVC()
# n_estimators = 10
# n_jobs = 5
# model = BaggingClassifier(estimator=estimator,
#                           n_estimators=n_estimators,
#                           max_samples=1./n_estimators,
#                           n_jobs=n_jobs)
# model.fit(X_train_scale,y_train)
# model.predict(X_train_scale)
# model.predict_proba(X_train_scale)

* base_estimator는 LinearSVC뿐만 아니라 다른 분류 모델들도 적용가능하다.
* n_estimators는 다수결을 수행할 estimator의 개수를 가리킨다.
* max_samples는 각 estimator를 만들 때 전체 튜플의 몇 %를 사용할 지를 입력받는다.
* n_jobs가 2이상인 경우가 병렬처리(multi-processing)이다.

In [24]:
# from xgboost import XGBRFClassifier
# from lightgbm import LGBMClassifier
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.ensemble import VotingClassifier
# from sklearn.model_selection import cross_val_score
# from sklearn.model_selection import GridSearchCV
# # import numpy as np

# # # 데이터 로드 및 전처리
# # # X_train, y_train = load_data()

# # # 모델 생성
# xgb_classifier = XGBRFClassifier()
# lgbm_classifier = LGBMClassifier()
# rf_classifier = RandomForestClassifier()

# # 하이퍼파라미터 튜닝 (예시로 일부 하이퍼파라미터만 설정)
# param_grid = {
#     'n_estimators': [100, 200, 300],
#     'max_depth': [10, 20, 30]
# }
# grid_search = GridSearchCV(rf_classifier, param_grid, cv=5)
# grid_search.fit(X_train, y_train)
# rf_best = grid_search.best_estimator_

# # 앙상블 모델 구성
# model = [('LGBM', lgbm_classifier), ('RF', rf_best)]

# voting_classifier = VotingClassifier(estimators=model, voting='hard', n_jobs=-1)

# # 교차 검증을 사용한 성능 평가
# cv_score = cross_val_score(voting_classifier, X_train, y_train, cv=10, scoring="accuracy", n_jobs=-1)
# print(f'Cross Validation Mean is {np.mean(cv_score)}')


In [25]:
# from sklearn.model_selection import cross_val_score

# svm_clf_linear_cross_val_scores = cross_val_score(model, X_train_scale, y_train, cv=10, scoring="accuracy")
# svm_clf_linear_cross_val_scores

## XGB, LGBM, RF  그리드서치

In [26]:
from xgboost import XGBRFClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import cross_val_score, GridSearchCV

# LGBMClassifier 및 RandomForestClassifier에 대한 그리드 서치를 수행할 매개변수 그리드 정의
new_lgbm_param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, 30]
}

new_rf_param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, 30]
}

# 그리드 서치를 사용하여 최적의 하이퍼파라미터 조합을 찾는다.
new_lgbm_grid_search = GridSearchCV(LGBMClassifier(random_state=42), new_lgbm_param_grid, cv=5, scoring="accuracy", n_jobs=-1)
new_lgbm_grid_search.fit(X_train, y_train)

new_rf_grid_search = GridSearchCV(RandomForestClassifier(random_state=42), new_rf_param_grid, cv=5, scoring="accuracy", n_jobs=-1)
new_rf_grid_search.fit(X_train, y_train)

# 최적의 모델과 하이퍼파라미터 출력
new_best_lgbm = new_lgbm_grid_search.best_estimator_
new_best_rf = new_rf_grid_search.best_estimator_
print("Best LGBM Classifier:", new_best_lgbm)
print("Best RandomForest Classifier:", new_best_rf)

# VotingClassifier를 업데이트하여 최적의 모델로 앙상블
new_model = [('LGBM', new_best_lgbm), ('RF', new_best_rf)]
new_votingC = VotingClassifier(estimators=new_model, voting='soft', n_jobs=-1)

# 교차 검증을 사용한 성능 평가
cv_score = cross_val_score(new_votingC, X_train, y_train, cv=10, scoring="accuracy", n_jobs=-1)
print(f'Cross Validation Mean is {np.mean(cv_score)}')


ModuleNotFoundError: No module named 'xgboost'

In [ ]:
# from sklearn.ensemble import ExtraTreesClassifier, GradientBoostingClassifier
# from sklearn.ensemble import VotingClassifier
# from sklearn.model_selection import cross_val_score
# import numpy as np

# # 모델 정의
# extra_trees_classifier = ExtraTreesClassifier(n_estimators=100, max_depth=30, n_jobs=-1, random_state=42)
# gradient_boost_classifier = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42)

# # 앙상블 모델 생성
# voting_classifier = VotingClassifier(estimators=[('etc', extra_trees_classifier), ('gbc', gradient_boost_classifier)], voting='soft')

# # 교차 검증 수행
# cv_scores = cross_val_score(voting_classifier, X_train, y_train, cv=10, scoring="accuracy", n_jobs=-1)

# # 각 폴드의 정확도 출력
# for i, fold_scores in enumerate(cv_scores, start=1):
#     print(f"Fold {i}: {fold_scores}")

# # 평균 정확도 출력
# print(f"Cross Validation Mean is {np.mean(cv_scores)}")


Fold 1: 0.9722916666666667
Fold 2: 0.9711666666666666
Fold 3: 0.9722916666666667
Fold 4: 0.972
Fold 5: 0.9720416666666667
Fold 6: 0.9728333333333333
Fold 7: 0.9735416666666666
Fold 8: 0.9735833333333334
Fold 9: 0.971375
Fold 10: 0.9719583333333334
Cross Validation Mean is 0.9723083333333333


[0.92275   , 0.92379167, 0.92325   , 0.922875  , 0.92275   ,
       0.92504167, 0.92458333, 0.92658333, 0.92429167, 0.92379167]

In [27]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
import numpy as np

# 모델 정의
extra_trees_classifier = ExtraTreesClassifier(n_estimators=100, max_depth=30, n_jobs=-1, random_state=42)
poly_kernel_svm_classifier = SVC(kernel="poly", degree=3, coef0=1, C=100, gamma='auto', max_iter=-1, probability=True)

# 앙상블 모델 생성
voting_classifier = VotingClassifier(estimators=[('etc', extra_trees_classifier), ('svc', poly_kernel_svm_classifier)], voting='soft')

# 교차 검증 수행
final_cv_scores = cross_val_score(voting_classifier, X_train, y_train, cv=10, scoring="accuracy", n_jobs=-1)

# 각 폴드의 정확도 출력
for i, score in enumerate(final_cv_scores, start=1):
    print(f"Fold {i}: {score}")

# 평균 정확도 출력
print(f"Cross Validation Mean is {np.mean(final_cv_scores)}")

Fold 1: 0.9902916666666667
Fold 2: 0.9889166666666667
Fold 3: 0.9902916666666667
Fold 4: 0.9905
Fold 5: 0.98875
Fold 6: 0.9910416666666667
Fold 7: 0.9903333333333333
Fold 8: 0.9909166666666667
Fold 9: 0.99025
Fold 10: 0.9894583333333333
Cross Validation Mean is 0.990075


##### 0.9900666666666667